### ISSUE TITLE
Markdown not working on Standard Notes web

### ISSUE THREAD

**Issue by onlinemumie** [standardnotes/app#1112]
Markdown notes show the following error code on Standard Notes web:

{"error":{"message":"Not found."}} 

On Standard notes desktop (version 3.20.0) and android (version 3.20.1), the markdown notes look normal.

**Comment by moughxyz** [comment]
Hmm which Markdown editor/type? Can you also open Dev Tools > Network tab in your browser and see which request URL it makes to get the editor?

**Comment by onlinemumie** [comment]
The markdows editor is Markdown Pro.

I'm not quite sure how to find the editor request url in DevTools -> Network.

Anyway, everything started to work again when I restarted the browswer, which I probably should have done first thing, so I guess this issue is solved.
