### ISSUE TITLE
[Desktop] Update check fails

### ISSUE THREAD

**Issue by makarandh** [standardnotes/app#1148]
When checking for update (Hamburger Menu -> Updates -> Check for updates), get the following error. (Please see screenshot).

<img width="358" alt="Screenshot_20220624_084918" src="https://user-images.githubusercontent.com/38956972/175502923-25ab2097-03f6-4416-98a7-1c72407006fc.png">

Environment: 
Debian Linux 11 (Bullseye)
KDE Plasma 5.20.5
Standard Notes: 3.22.11

**Comment by moughxyz** [comment]
Can you try again now?

**Comment by makarandh** [comment]
Thanks! Issue is fixed.
