### ISSUE TITLE
Too many releases

### ISSUE THREAD

**Issue by goremykin** [standardnotes/app#1149]
Do you really need to create so many releases every day?
I subscribed to new releases and sometimes I get several notifications in one hour

**Comment by moughxyz** [comment]
> Do you really need to create so many releases every day?

Yes, it's automated.

> I subscribed to new releases and sometimes I get several notifications in one hour

I recommend unsubscribing and following releases via another mechanism, like Twitter/blog for major releases and the in-app autoupdate mechanism.
