### ISSUE TITLE
Files upload through "Files navigation" count to space even after delete

### ISSUE THREAD

**Issue by DanielNetoP** [standardnotes/app#1154]
The files that are uploaded through the Labs feature `Files navigation` count towards the space even after you delete them through the Files view.
If you use the Top right button of the attachments and click delete permanently it deletes it and regains the storage of the file size.

**Comment by moughxyz** [comment]
Hmm good catch, we'll take a look at this.

**Comment by moughxyz** [comment]
Fixed in latest release.
