### ISSUE TITLE
Two parts in backup by email

### ISSUE THREAD

**Issue by khlinuxdeveloper** [standardnotes/app#1155]
Since June 19 I have received **two separate backup files by email**; they are divided into two parts.

Is this normal? In case I need to import the backup, how to select the two files?

Before I received one file of 7MB, now they are divided in two: 5MB (part 1) and 2MB (part 2).

_When I make a backup from the application, it only generates a 7MB file._

Screenshot: ![2FilesBackup](https://user-images.githubusercontent.com/68512577/175754318-0f84f8ec-f1b4-48db-bc9a-dbd84e386af3.png)

**Comment by moughxyz** [comment]
The per-email limit is just around 7MB, so anything greater will be divided up into multiple emails.

**Comment by khlinuxdeveloper** [comment]
I understand. Thank you very much for the clarification
