### ISSUE TITLE
Docker image hosted on ghcr.io

### ISSUE THREAD

**Issue by peterprumbach** [standardnotes/app#1216]
It would be great if it could provide a ready-built Docker image in the future. This only requires the use of GitHub Actions. This image can then be stored in the GitHub Container Registry for each release.

**Comment by peterprumbach** [comment]
Perhaps this is the equivalent [image](https://hub.docker.com/r/standardnotes/web). However, this is not sufficiently documented.

**Comment by moughxyz** [comment]
Documented here: https://github.com/standardnotes/app#docker-setup
