### ISSUE TITLE
Broken themes on editor area

### ISSUE THREAD

**Issue by gridlocdev** [standardnotes/app#1229]
In the web client, themes for all features except for Plain Text are currently broken for the editor area.

**Browser(s)**: Chromium v103, Firefox v102
**Client Version:** 3.38.3

![image](https://user-images.githubusercontent.com/60323737/177869933-18bbfea1-cb71-4a1b-94df-893af8cb08d0.png)
![image](https://user-images.githubusercontent.com/60323737/177870001-46df1fb1-720f-4b0c-8fcf-ee2be11335bd.png)

**Comment by moughxyz** [comment]
Thanks, will be fixed by https://github.com/standardnotes/app/commit/3d49b95bc593d67e949b2eec4a086ff25275eadf, which should finish deploying in under an hour.
