### ISSUE TITLE
“View v3.23.61 Release Notes” leads to a 404 page

### ISSUE THREAD

**Issue by StephenLittBelch** [standardnotes/app#1313]
In the Desktop app v3.23.21, clicking on “View v3.23.61 Release Notes” from the Updates menu opens a web browser to https://github.com/standardnotes/app/releases/tag/v3.23.21. With the new release tag structure of “Desktop X.XX.XX” the above URL may need updating. Thank you!

(The correct URL for v3.23.61, for example, now appears to be: https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.23.61)

**Comment by moughxyz** [comment]
This is fixed in the latest version.
