### ISSUE TITLE
add an option to disable text drag and drop

### ISSUE THREAD

**Issue by andy-goryachev** [standardnotes/app#1379]
For people who use Cut/Copy/Paste popup menus exclusively, the use of text drag and drop feels a bit disruptive.  I think this should be an option that can be turned off.

**Comment by haflaxa** [comment]
To clarify... @andy-goryachev

- What app are you using—web, mobile, desktop?
- What platform are you using SN on?
- Is it possible for you to share a screen capture of the behavior you're encountering? — _I'm having a hard time understanding what's happening on your end and this could help me get a better grasp of the what's going on_.

Thanks! 🙏

**Comment by andy-goryachev** [comment]
please disregard.  i got spooked by the cursor changing shape to indicate a DnD edit, it actually does not edit the text.
sorry.
